apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger 
spec:
  strategy: production
  collector:
    maxReplicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: url 
    secretName: jaeger-secret 
---
apiVersion: v1
kind: Secret
metadata: 
  name: jaeger-secret
data:
  ES_PASSWORD: mypass 
  ES_USERNAME: myuser 
type: Opaque
